### ISSUE TITLE
[Bug]: 崩溃

### ISSUE THREAD

**Issue by JeiFing** [SourceLandDev/AutoReload#1]
### Describe the bug

会导致服务器崩溃

### To Reproduce

当工具耐久（打火石、剪刀）消耗完的瞬间（背包里没有可替代的同种工具），服务器后台直接闪退。我的服务器版本为1.20.81，LeviLamina版本为0.12.2（之前bds 1.20.81+ll3 0.12.0版本也出现过同样的问题，但是未能查明具体原因）

### Expected behavior

希望能修复这个bug

### Platform

win 10 企业版 22H2

### BDS Version

1.20.81.01

### LeviLamina Version

0.12.2

### Version

1.1.7

**Comment by Yuisyuu** [comment]
未能复现，请安装crashlogger并提供trace log

**Comment by JeiFing** [comment]
这是我之前的插件，应该是文件出了点问题，重装后解决。抱歉！
________________________________
发件人: 予纾 ***@***.***>
发送时间: 2024年5月6日 10:00
收件人: SourceLandDev/AutoReload ***@***.***>
抄送: JeiFing ***@***.***>; Author ***@***.***>
主题: Re: [SourceLandDev/AutoReload] [Bug]: (Issue #1)


未能复现，请安装crashlogger并提供trace log

―
